Simplify client dependency resolution a bit.
Polymer/web-component-tester pull request #695
Opened 2018-04-03 17:34 UTC by justinfagnani

Hopefully this avoids some Windows issues, like #694

 - [ ] CHANGELOG.md has been updated

2018-04-03 20:18 UTC, rictic commented
Looks like we added appveyor but it's not configured properly?

Also we're getting 6.6.0-pre.3 for the client-side, which isn't in the acceptable version range for our client in package.json

2018-04-03 21:39 UTC, e111077 requested changes

2018-04-03 21:39 UTC, e111077 commented on runner/config.ts
> +        resolve.sync(npmPackage, {basedir: wctBrowserPackageDirPath});
Does this work when the filename is not the `main` in the package?

2018-04-04 01:26 UTC, e111077 requested changes

2018-04-04 01:26 UTC, e111077 commented on runner/config.ts
> +    // const absoluteBasePath =
please remove

2018-04-12 19:25 UTC, aomarks commented
Do we still want this PR? cc @usergenic who is doing wct surgery right now.

2019-01-03 17:18 UTC, aomarks commented
Closing this pull request because this repo is now archived. If this PR is still active, please submit a new one at https://github.com/Polymer/tools.

2019-01-03 17:18 UTC, closed without merging